services:
  db:
    image: postgres:17-alpine
    container_name: carbon-flama-db
    restart: always
    environment:
      POSTGRES_USER: carbon_user
      POSTGRES_PASSWORD: carbon_password
      POSTGRES_DB: carbon_flama
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carbon_user -d carbon_flama"]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  pgdata:
